- name: manage apt packages
  hosts: all
  become: true
  tasks: 
    - name: apt management
      ansible.builtin.apt:
        pkg: "{{ pkg | default(omit) }}"
        autoremove: "{{ autoremove | default(false) }}"
        autoclean: "{{ autoclean | default(false) }}"
        update_cache: "{{ update | default(false) }}"
        state: "{{ state | default('present') }}"
        #upgrade: "{{ upgrade | default('no') }}"
        deb: "{{ deb | default(omit)}}"

        


