- name: user 
  hosts: containers
  become: true
  tasks:
    - name: user 
      ansible.builtin.user:
        append: "{{ append | default(false) }}"
        name: "{{ user }}"
        uid: "{{ uid | default(omit) }}"
        group: "{{ primary_grp | default(omit)}}"
        groups: "{{ multiple_grp | default('') }}"
        state: "{{ state | default('present') }}"
        force: "{{ force | default(false) }}"
        remove: "{{ remove | default(false) }}"
        system: "{{ root | default(false) }}"
        password: "{{ password | password_hash('sha512') |default(omit)}}"



 

      
        

