- name: manager user accounts on nginx servers 
  hosts: "{{ hosts }}"
  tasks:
    - name: configure user account  
      ansible.builtin.user:
        append: "{{ append | default(false) }}"
        user: "{{ user }}"
        uid: "{{ uid | default(omit) }}"
        group: "{{ primary_group | default(omit)}}"
        groups: "{{ multiple_group | default('') }}"
        state: "{{ state | default('present') }}"
        force: "{{ force | default(false) }}"
        remove: "{{ remove | default(false) }}"
        system: "{{ root | default(false) }}"
        password: "{{ password  | password_hash('sha512', password) }}"
        



 

      
        

